version: '2'

services:

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"

  cdmi-server:
    container_name: cdmi-server

    dns_search: local.io

    build:
      context: .
      dockerfile: ./docker/storm-cdmi-server/Dockerfile
      args:
        YAML_CONFIG_FILE: ${YAML_CONFIG_FILE}
        STORM_CONFIG_FILE: ${STORM_CONFIG_FILE}
        STORM_CAPABILITIES_FILE: ${STORM_CAPABILITIES_FILE}
        CDMI_SERVER_PORT: ${CDMI_SERVER_PORT}
    ports:
      - "${EXTERNAL_PORT}:${CDMI_SERVER_PORT}"
    depends_on:
      - redis
    extra_hosts:
      - "${STORM_BACKEND_HOSTNAME}:${STORM_BACKEND_IPADDR}"
