spring:
  profiles:
    active: redis
    
server:
  port: 8888

rest:
  user: restadmin
  pass: restadmin
  
cdmi:
  qos:
    backend:
      type: storm
  data:
    baseDirectory: /tmp/cdmi
---
spring:
  profiles: redis
  redis:
    port: 6379
    host: redis
