spring:
  profiles:
    active: redis

logging:
  level:
    edu.kit.scc: INFO
    org.snia: INFO
    it.grid.storm: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %c{1}:%L - %msg%n"

server:
  port: 8888

rest:
  user: restadmin
  pass: RESTADMIN_PASSWORD

cdmi:
  qos:
    backend:
      type: storm
  data:
    baseDirectory: /tmp/cdmi

oidc:
  tokeninfo: https://iam-test.indigo-datacloud.eu/introspect
  userinfo: https://iam-test.indigo-datacloud.eu/userinfo 
  clientid: YOUR-REGISTERED-CLIENTID
  clientsecret: YOUR-REGISTERED-CLIENTSECRET

---
spring:
  profiles: redis
  redis:
    port: 6379
    host: redis
